### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by amclain** [ElixirSeattle/xebow#21]
@doughsay & @dhedlund: Considering this project doesn't have unit tests yet, how would you feel if I implemented [ESpec](https://github.com/antonmi/espec) and configured CI? I've enjoyed using this library on other projects, and its [mocks](https://github.com/antonmi/espec#mocks) are a nice way to work around physical hardware components that aren't available during the CI run. I've also found the ESpec style of testing (inspired by [RSpec](https://rspec.info/)) pleasant to read as well, but I realize that's subjective.

What are your thoughts?

**Comment by doughsay** [comment]
"...the main idea is to be close to its perfect DSL". Wow, there's some wild opinions flying around in here, eh?

Personally I feel the rspec syntax gets really unwieldy for larger more complicated tests.  Having to scroll all the way up to see what the "before" or "context" is just to understand a deeply nested test is super annoying...

I don't think regular ExUnit does it any better though, tests can just get messy no matter what...

I dunno... I'm very hesitant to want to try something new with testing since I've been writing exclusively ExUnit tests since I first started writing Elixir...

**Comment by amclain** [comment]
>"...the main idea is to be close to its perfect DSL". Wow, there's some wild opinions flying around in here, eh?

Lol, I think the intent was supposed to mean that ESpec is as close to the RSpec DSL as possible, not that the RSpec DSL is the one true DSL for all to follow. :stuck_out_tongue_winking_eye: 

>Having to scroll all the way up to see what the "before" or "context" is just to understand a deeply nested test is super annoying...

:thinking:  There may have been a better way to organize the tests in that case. I personally try to avoid deep nesting. Code folding in a text editor that supports it may also help. But yeah, deeply nested tests in any test suite can be a pain.

>I dunno... I'm very hesitant to want to try something new with testing since I've been writing exclusively ExUnit tests since I first started writing Elixir...

I've been writing ESpec tests almost exclusively with Elixir (I switched to RSpec when doing Ruby and had really good experiences with it), so ok, I can be the one who tries something different.

Question around that then:
How do you want to handle libraries/modules that exist for `:target` when the app is running on the hardware, but not for `:host` when the tests run? Are you ok with using mocks for that, or do you prefer another method?

**Comment by amclain** [comment]
Update from the architecture meeting: [Mox](https://hex.pm/packages/mox) is a library we can move forward with.

**Comment by amclain** [comment]
Resolved by #23.
