### ISSUE TITLE
Key presses are occasionally triggered twice

### ISSUE THREAD

**Issue by amclain** [ElixirSeattle/xebow#32]
After pressing arbitrary keys for a while, every now and then one of the key presses ends up triggering twice. It doesn't matter if the keys are pressed fast or slow, and I have also tried varying the timing between different key presses. It feels like the issue happens more often after a small pause, but that may just be coincidence. The first few occurrences in the sequence in the screenshot seem to happen just after 50 characters, but that may also be coincidence. In the 123, 456, 789 sequence it feels like 1, 7, 5 trigger the most often. I have tried combinations of keys that are not in that group, like 2, 6, 8, and see the same issue of keys triggering twice. I have also tried the keybow on a couple different surfaces to try to eliminate mechanical bouncing of the keys if that was potentially an issue.

![image](https://user-images.githubusercontent.com/4755047/85096082-18fbd200-b1a8-11ea-8847-32ca176b1218.png)

Is anyone else able to reproduce this?

**Comment by doughsay** [comment]
I'll try, but I'm not surprised by this.  Mechanical switches just do this, and it's really hard to fix it 100% of the time. (from what I understand)

In the case of the kebow, I used the ElixirCircuits GPIO interrupt mechanism.  This has built in "glitch suppression" (see the docs here: https://hexdocs.pm/circuits_gpio/Circuits.GPIO.html#set_interrupts/3), but I have no idea how good it is, it may occasionally let some glitches through.

In the case of the full-matrix scanning technique used by things like QMK and other mechanical keyboards, you have to implement manual debouncing.  Here's where I had to do that for my other keyboard: https://github.com/doughsay/keyboard/blob/master/firmware/lib/excalibur/firmware/matrix_server.ex#L129 (without debouncing I would get double-presses).

I was under the impression that no matter what, you had to do SOME kind of software debouncing, because mechanical electrical switches do just sometimes cause multiple activations in quick succession.

**Comment by amclain** [comment]
Gotcha, I wasn't sure if debouncing had been implemented or not yet and if it could have been a software issue. Thanks for confirming where to start.

>I was under the impression that no matter what, you had to do SOME kind of software debouncing, because mechanical electrical switches do just sometimes cause multiple activations in quick succession.

Yeah, exactly. I hooked a switch (not a Keybow one) up to the oscilloscope to illustrate this for you and anyone else who may not have seen a waveform of it before. All those spikes are the electrical contacts in the switch literally bouncing back and forth before settling in the right position.

![image](https://user-images.githubusercontent.com/4755047/85104922-54090000-b1be-11ea-9962-3a92c0c69f5c.png)

It _is_ possible to debounce in-circuit with capacitors, but I don't see any on this board and you're right, software debouncing is probably the way to go for this case. Tuning the Circuits.GPIO glitch suppression sounds like a good place to start.

**Comment by amclain** [comment]
I measured some actual Keybow keys.

Here's what most of the key presses look like (really good):
![F0006TEK](https://user-images.githubusercontent.com/4755047/85900670-0dfefe00-b7b5-11ea-9bab-a5edc6dd1f70.jpg)

Every now and then there's some noise. Most of the time it's 2.5ms or less; sometimes it's a little longer.

![F0007TEK](https://user-images.githubusercontent.com/4755047/85900736-296a0900-b7b5-11ea-8f34-b1c94575936d.jpg)

![F0008TEK](https://user-images.githubusercontent.com/4755047/85900746-2cfd9000-b7b5-11ea-9f39-ded8a1316827.jpg)

![F0012TEK](https://user-images.githubusercontent.com/4755047/85900776-3850bb80-b7b5-11ea-9b72-45ec8d7e56c2.jpg)

**Comment by amclain** [comment]
@doughsay you were totally right. The issue was with debouncing.
